menginstal ansible di **worktation**
membuat folder dan **invantory** di dalamnya

di **invantory** ketikan ip kita
`192.168.1.1`
`192.168.1.2`

menggunakna command :
`ansible all --key-file ~/.ssh/ansible -i inventory -m ping`
apa gunanya?

untuk melihat konkesi anatara server server nya

membuat file **ansible.cfg**

[default]
inventory = inventory
private_key_file = ~/.ssh/ansible

tinggal mengetikan gampang `ansible all -m ping`

ansible all -m gather_facts
ansible all -m gather_facts --limit 192.168.1.1

mengubah konfigurasi server menggunakan edhoc
konfigrasi premession nya dengan mengetikan

ansible all -m apt -a update_cahce=true --become --ask-become-pass
maka akan menanyakan password kita yang ditanyakan

dokumentasi ansible: https://docs.ansible.com/ansible/latest/network/getting_started/index.html
https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html

mendownload vim
*ansible all -m apt -a name=vim-nox --become  --ask-become-pass*
lihat asli aslinya
dan juga instal yang lain tapi sudah ada gimana akibatnya

lalu lihat hasil log nya di /var/log/apt

untuk mengintsal yang lebih lama

