menginstal ansible di **worktation**
membuat folder dan **invantory** di dalamnya

di **invantory** ketikan ip kita
`192.168.1.1`
`192.168.1.2`

menggunakna command :
`ansible all --key-file ~/.ssh/ansible -i inventory -m ping`
apa gunanya?

untuk melihat konkesi anatara server server nya

membuat file **ansible.cfg**

[default]
inventory = inventory
private_key_file = ~/.ssh/ansible

tinggal mengetikan gampang `ansible all -m ping`

ansible all -m gather_facts
ansible all -m gather_facts --limit 192.168.1.1
