# inventory
[ip add srv1]
[ip add srv1]

# command melihat koneksi
ansible all --key-file ~/.ssh/ansible -i inventory -m ping

# isi file ansible
[default]
inventory = inventory
private_key_file = ~/.ssh/ansible

# command melihat koneksi
ansible all -m ping


# command untuk mengumpulkan informasi server
ansible all -m gather_facts
ansible all -m gather_facts --limit 192.168.1.1


# update server
ansible all -m apt -a update_cahce=true --become --ask-become-pass

dokumentasi ansible: https://docs.ansible.com/ansible/latest/network/getting_started/index.html
https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html



# menginstall dengan adhoc
install : ansible all -m apt -a "name=bind9 state=present update_cache=true" --become --ask-become-pass
install versi terbaru:  state=latest
remove: state=absent
purge: purge=yes